name: Update VPNGate List

on:
  schedule:
    - cron: '18-24/10 * * * *'  # 每10分钟运行一次
    - cron: '8-18/5 * * * *'
    - cron: '0-8/20 * * * *'
  push:
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Step 3: 拉取并更新 VPNGate 数据
    - name: Fetch VPNGate data and update CSV
      run: python fetch_vpngate.py


      # 修改 README.md 文件
    - name: Update README.md
      run: |
        #export TZ=Asia/Shanghai
        echo "# $(basename $GITHUB_REPOSITORY)" > README.md
        echo "" >> README.md
        echo "The servers.csv file was last updated at $(TZ=Asia/Shanghai date +"%Y-%m-%d %H:%M:%S") UTC+8." >> README.md
   
    # Step 4: 提交并推送更新（仅在文件变更时）
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update servers list"
        add: |
          requirements.txt
          servers.csv
          README.md
